config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('student/items/', views.ItemsView.as_view(), name='items_view'),
    path('student/reunions/', views.ReunionsView.as_view(), name='reunions_view'),
    path('student/reunion/<int:pk>/', views.ReunionDetailView.as_view(), name='reunion-detail'),

]

teacher/urls.py
from django.urls import path

from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('rating/', views.RatingCreateView.as_view(), name='rating-create'),
    path('lesson/', views.LessonCreateView.as_view(), name='lesson-create'),
    path('lessons/', views.TeacherLessonsView.as_view(), name='lessons'),
    path('rating/<int:pk>/', views.RatingUpdateView.as_view(), name='rating-update'),
    path('lesson/<int:pk>/', views.LessonUpdateView.as_view(), name='lesson-update'),
    path('exam/<int:pk>/', views.ExamUpdateView.as_view(), name='exam-update'),
    path('exam/', views.ExamCreateView.as_view(), name='exam-create'),
    path('promote/', views.StudentsYearView.as_view(), name='promote'),
    path('student-details/<int:pk>/', views.StudentDetailView.as_view(), name='student-details'),
    path('exams/', views.TeacherExamsView.as_view(), name='exams'),
    path('exam/rating/<int:pk>/', views.ExamRatingUpdate.as_view(), name='exam-rating-update'),
    path('student/promote/<int:pk>/', views.PromoteView.as_view(), name='student-promote'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('', views.PasswordChange.as_view(), name='change_password'),
    path('academic-year/', views.ChooseAcademicYear.as_view(), name='change_academic_year'),
]

student/models.py
from django.db import models
from django.conf import settings


class Student(models.Model):
    """school student model inherited from the user model"""

    class Confession(models.IntegerChoices):
        NOT_DEFINED = -1
        ROMAN_CATHOLIC = 0
        GREEK_CATHOLIC = 1
        ORTHODOX = 2
        OTHER = 3

    class Education(models.IntegerChoices):
        HIGHER = -1
        SECONDARY = 0
        VOCATIONAL = 1
        PRIMARY = 2
        OTHER = 3

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    academic_years = models.ManyToManyField('AcademicYear', related_name='students')
    phone = models.CharField(max_length=24)
    birth_date = models.DateField()
    confession = models.IntegerField(choices=Confession.choices, default=-1)
    education = models.IntegerField(choices=Education.choices, default=-1)
    address = models.TextField(blank=True)
    workplace = models.TextField(blank=True)
    comments = models.TextField(blank=True);
    index = models.CharField(max_length=24, blank=True, unique=True)
    diploma = models.CharField(max_length=24, blank=True, unique=False)
    level = models.ForeignKey('Level', related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} - level {self.level}"


class AcademicYear(models.Model):
    """We can manage academic years"""
    name = models.CharField(max_length=12)
    started_at = models.DateField()
    finished_at = models.DateField()
    items = models.ManyToManyField('Item', related_name='academicyears', through='StudentItemYear')

    def __str__(self):
        return f'{self.name}'


class Level(models.Model):
    """The school has three levels"""

    class LevelNumber(models.IntegerChoices):
        FIRST = 1
        SECOND = 2
        LAST = 3

    level_number = models.IntegerField(choices=LevelNumber.choices, default=1)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE, related_name="levels")

    def __str__(self):
        return f"{self.level_number} {self.academic_year}"


class Item(models.Model):
    """Model to manage school items"""
    name = models.CharField(max_length=128)
    students = models.ManyToManyField(Student, through='StudentItemYear', related_name='items')

    def __str__(self):
        return f"{self.name}"


class StudentItemYear(models.Model):
    """model describing M2M relationship between student, academic years and items """
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE)

    class Meta:
        """only one item student pair is possible in given academic year"""
        unique_together = ('student', 'item', 'academic_year',)

    def __str__(self):
        return self.student.user.first_name + " " + self.student.user.last_name + " " + " " + self.item.name + " " + self.academic_year.name

teacher/models.py
from django.db import models
from django.conf import settings
from student.models import Item, AcademicYear, Level, Student


class Teacher(models.Model):
    """teachers in shool inherited forom the user model. It is possible the former student to become a teacher"""
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=24)

    class Degree(models.IntegerChoices):
        MASTER = -1
        DOCTOR = 0
        PROFESSOR = 1
        OTHER = 2

    degree = models.IntegerField(choices=Degree.choices, default=-1)
    items = models.ManyToManyField(Item, through='TeacherItemYear', related_name='teachers')

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class TeacherItemYear(models.Model):
    """Model describing M2M relationship between Teacher and items in given academic year """
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE)

    class Meta:
        """only one entry for item to specific teacher in given academic year is possible"""
        unique_together = ('teacher', 'item', 'academic_year')

    def __str__(self):
        return f"{self.academic_year} - {self.teacher} - {self.item}"


class Rating(models.Model):
    """ratings for students"""
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='ratings')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='ratings')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='ratings')
    date = models.DateField()
    value = models.DecimalField(max_digits=3, decimal_places=2)
    notice = models.TextField()

    def __str__(self):
        return f"{self.student} - {self.item} - {self.date}: {self.value}"


class Lesson(models.Model):
    """lessons for item in specific reunion"""
    localization = models.ForeignKey('Localization', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='lessons')
    level = models.ForeignKey(Level, on_delete=models.CASCADE, related_name='lessons')
    reunion = models.ForeignKey('Reunion', on_delete=models.CASCADE, related_name='lessons')
    present_students = models.ManyToManyField(Student, related_name='lessons')
    topic = models.CharField(max_length=128)
    date_time = models.DateTimeField()
    references = models.FileField(upload_to="student", blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='lessons')

    def __str__(self):
        return f"{self.item} - {self.topic}"


class Reunion(models.Model):
    """weekend's reunions"""
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE, related_name="reunions")
    level = models.ForeignKey(Level, on_delete=models.CASCADE, related_name='reunions')
    start_at = models.DateField()
    finish_at = models.DateField()

    def __str__(self):
        return f"{self.academic_year} {self.level}: {self.start_at} - {self.finish_at}"


class Localization(models.Model):
    """Localizations for lessons and exams"""
    name = models.CharField(max_length=128)
    address = models.TextField()

    def __str__(self):
        return f"{self.name}"


class Exam(models.Model):
    """Exams"""
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE)
    localization = models.ForeignKey(Localization, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='exams')
    date_time = models.DateTimeField()
    students = models.ManyToManyField(Student, through='StudentExam', related_name='exams')

    def __str__(self):
        return f"{self.academic_year} - {self.item}"


class StudentExam(models.Model):
    """model describing the M2M relationship beetween student and exam. The rating may be corrected until the exam is marked as passed"""
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    is_passed = models.BooleanField(default=False)

    class Meta:
        unique_together = ('student', 'exam',)

    def __str__(self):
        return f"{self.student} - {self.exam}: {self.rating}"

teacher/forms.py
from django.forms import DateInput, DateTimeInput
from django.forms import ModelForm, Form

from .models import Rating, Lesson, Exam


class DateInput(DateInput):
    input_type = 'date'


class DateTimeInput(DateTimeInput):
    input_type = 'datetime-local'


class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ('student', 'teacher', 'item', 'date', 'value', 'notice')
        widgets = {
            'date': DateInput(),
        }


class LessonForm(ModelForm):
    class Meta:
        model = Lesson
        fields = (
            'localization', 'reunion', 'level', 'date_time', 'teacher', 'item', 'topic', 'references')
        widgets = {
            'date_time': DateTimeInput(),
        }


class LessonUpdateForm(ModelForm):
    class Meta:
        model = Lesson
        fields = (
            'localization', 'reunion', 'level', 'date_time', 'teacher', 'item', 'topic', 'present_students',
            'references')
        widgets = {
            'date_time': DateTimeInput(),
        }


class ExamForm(ModelForm):
    class Meta:
        model = Exam
        fields = (
            'academic_year', 'localization', 'date_time', 'item', 'students')
        widgets = {
            'date_time': DateTimeInput(),
        }


class EmptyForm(Form):
    pass

student/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views import View
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings

from teacher.models import Rating, Exam, StudentExam, Reunion, Teacher
from utlis import TeacherTestMixin, StudentTestMixin
from .models import AcademicYear, Item


# Create your views here.
class HomeView(StudentTestMixin, View):
    """Default view for all project. It redirects to correct view after successfull login """

    def get(self, request):
        current_academic_year = AcademicYear.objects.all().order_by('-started_at').first()
        if current_academic_year:
            request.session['current_academic_year'] = current_academic_year.name
        else:
            request.session['current_academic_year'] = "No academic year selected"
        return redirect(reverse('student:items_view'))

    def handle_no_permission(self):
        if TeacherTestMixin.is_teacher(self):
            return redirect(reverse('teacher:home'))
        elif self.request.user.is_superuser:
            return redirect(reverse('teacher:promote'))
        else:
            return redirect(reverse('users:login'))


class ItemsView(StudentTestMixin, View):
    """Items of logged student in chosen academic year"""

    def get(self, request):
        # check if user is a student, if not redirect him to login page
        current_academic_year = AcademicYear.objects.filter(name=request.session.get('current_academic_year')).first()
        items = Item.objects.filter(
            Q(academicyears__in=[current_academic_year]) & Q(students__in=[request.user.student])).order_by('name')
        ratings = Rating.objects.filter(student=request.user.student)
        exams = Exam.objects.filter(students__in=[request.user.student]).filter(academic_year=current_academic_year)
        ratings_exams = StudentExam.objects.filter(student=request.user.student)
        return render(request, 'student/home.html',
                      context={'ratings': ratings, 'items': items, 'exams': exams, 'ratings_exams': ratings_exams,
                               'is_student': True})


class ReunionsView(StudentTestMixin, ListView):
    """reunions in current academic year for logged students"""
    template_name = 'student/reunion_list.html'

    def queryset(self):
        current_academic_year = AcademicYear.objects.filter(
            name=self.request.session.get('current_academic_year')).first()
        queryset = Reunion.objects.filter(academic_year=current_academic_year).filter(
            level=self.request.user.student.level)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['is_student'] = True
        return context

    context_object_name = 'reunions'


class ReunionDetailView(StudentTestMixin, DetailView):
    """Details of specific reunion"""
    model = Reunion
    template_name = 'student/reunion_details.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['is_student'] = True
        return context

    context_object_name = 'reunion'

teacher/templates/teacher/exam_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create/Update exam:</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
{% endblock %}

teacher/templates/teacher/exams.html
{% extends 'base.html' %}

{% block title %}
    Student|Reunion detail 2
{% endblock %}
{% block content %}
    <h3>Exams of items where You are a teacher: <a style="float:right;" href="{% url 'teacher:exam-create' %}">
        <button class="btn btn-danger btn-sm">CREATE EXAM</button>
    </a></h3>
    <table class="table">

        {% for exam in exams|dictsortreversed:'date_time' %}
            <thead class="thead-dark">
            <tr class="table-dark">
                <th scope="col" colspan="4">{{ exam.item }}</th>
            </tr>

            <tr>
                <th>DATE TIME</th>
                <th>Localization</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            <tr>
                <th scope="row">{{ exam.date_time }}</th>
                <td>{{ exam.localization }}<br/>{{ exam.localization.address }}</td>
                <td><a href="{% url 'teacher:exam-update' pk=exam.id %}">
                    <button class="btn btn-sm btn-danger">UPDATE EXAM</button>
                </a>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <div class="accordion" id="accordion{{ forloop.counter }}">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true"
                                        aria-controls="collapse{{ forloop.counter }}">
                                    Students accessed to exam:
                                </button>
                            </h2>
                            <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
                                 aria-labelledby="heading{{ forloop.counter }}"
                                 data-bs-parent="#accordion{{ forloop.counter }}">
                                <div class="accordion-body">
                                    {% for student in exam.students.all|dictsort:'user.last_name' %}
                                        <table class="table table-sm">
                                            <thead><th>Student</th><th>RATING</th><th></th></thead>
                                            {% for studentexam in student.studentexam_set.all %}
                                                {% if studentexam.exam.pk == exam.pk %}
                                                    <tr>
                                                        <td>{{ student.user.first_name }} {{ student.user.last_name }}</td>
                                                        <td>{{ studentexam.rating }}</td>
                                                        <td>
                                                            <a href="{% url 'teacher:exam-rating-update' pk=studentexam.pk %}">
                                                                <button class="btn btn-sm-sm btn-danger">UPDATE RATING
                                                                </button>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                        </table>
                                    {% empty %}
                                        <p>There is no student accessed yet</p>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

teacher/templates/teacher/home.html
{% extends 'base.html' %}
{% load teacher_extras %}

{% block title %}
    Student|Home
{% endblock %}

{% block content %}

    {% if is_teacher %}
        <h1>Your students by items with their ratings:</h1>
    {% else %}
        <h1>You are not a teacher</h1>
    {% endif %}

    {% for item in items %}
        <table class="table table-sm">

            <thead class="thead-dark">
            <tr>
                <th scope="col" colspan="4">{{ item.name }}</th>
            </tr>

            <tr>
                <th>FIRST NAME</th>
                <th colspan="2">SECOND NAME</th>
                <th>NOT PRESENT</th>
            </tr>
            </thead>
            <tbody>

            {% for student in item.students|for_academic_year:request.session.current_academic_year %}
                {% for student_item in student.items_p %}
                    {% if student_item.ide == item.pk %}
                        <tr class="table-warning">
                            <td>{{ student.user.first_name }}</td>
                            <td colspan="2">{{ student.user.last_name }}</td>
                            <td>{{ student_item.not_present }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <tr>
                    <th colspan="4">RATINGS</th>
                </tr>
                <tr>
                    <th>DATE</th>
                    <th>VALUE</th>
                    <th>NOTICE</th>
                    <th></th>
                </tr>
                {% for rating in ratings|for_student:student %}
                    <tr>
                        <td>{{ rating.date }}</td>
                        <td>{{ rating.value }}</td>
                        <td>{{ rating.notice }}</td>
                        <td><a href="{% url 'teacher:rating-update'  pk=rating.id %}">
                            <button class="btn btn-danger btn-sm">EDIT</button>
                        </a></td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>

    {% endfor %}

{% endblock %}

teacher/templates/teacher/lesson_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create/Update lesson:</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
{% endblock %}

teacher/templates/teacher/lessons.html
{% extends 'base.html' %}

{% block title %}
    Student|Reunion detail 2
{% endblock %}
{% block content %}
    <h3>Lessons where You are the teacher: <a style="float:right;" href="{% url 'teacher:lesson-create' %}">
        <button class="btn btn-danger btn-sm">CREATE LESSON</button>
    </a></h3>
    <table class="table">

        {% for lesson in lessons|dictsortreversed:'date_time' %}
            <thead class="thead-dark">
            <tr class="table-dark">
                <th scope="col" colspan="4">{{ lesson.item }}</th>
            </tr>
            <tr class="table-secondary">
                <th scope="col" colspan="4">{{ lesson.topic }}</th>
            </tr>
            <tr>
                <th>DATE TIME</th>
                <th>Localization</th>
                <th>References</th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            <tr>
                <th scope="row">{{ lesson.date_time }}</th>
                <td>{{ lesson.localization }}<br/>{{ lesson.localization.address }}</td>
                {% if lesson.references %}
                    <td><a href="{{ MEDIA_URL }}{{ lesson.references }}" download>DOWNLOAD</a></td>
                {% else %}
                    <td></td>
                {% endif %}
                <td><a href="{% url 'teacher:lesson-update' pk=lesson.id %}">
                    <button class="btn btn-sm btn-danger">UPDATE</button>
                </a></td>
            </tr>
            <tr>
                <td colspan="4">
                    <div class="accordion" id="accordion{{ forloop.counter }}">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="true"
                                        aria-controls="collapse{{ forloop.counter }}">
                                    Present students:
                                </button>
                            </h2>
                            <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
                                 aria-labelledby="heading{{ forloop.counter }}"
                                 data-bs-parent="#accordion{{ forloop.counter }}">
                                <div class="accordion-body">
                                    {% for student in lesson.present_students.all|dictsort:'user.last_name' %}
                                        <p>{{ student.user.first_name }} {{ student.user.last_name }}</p>
                                    {% empty %}
                                        <p>There is no student present yet</p>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

teacher/templates/teacher/rating_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create/Update rating:</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
{% endblock %}

teacher/templates/teacher/student.html
{% extends 'base.html' %}

{% block title %}
    Student|Reunion detail 2
{% endblock %}
{% block content %}
    <h3>Student {{ student.user.first_name }} {{ student.user.last_name }}</h3>
    <table class="table">

        {% for exam in exams %}
            <thead class="thead-dark">
            <tr class="table-dark">
                <th scope="col" colspan="3">{{ exam.exam.item.name }}</th>
            </tr>
            <tr>
                <th>PASSED?</th>
                <th>RATING</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ exam.is_passed }}</td>
                    <td>{{ exam.rating }}</td>
                    <td></td>
                </tr>

        {% endfor %}
                <tr>
                <td colspan="3"><a href="{% url 'teacher:student-promote' pk=student.id %}">
                        <button class="btn btn-sm btn-danger">PROMOTE TO THE NEXT LEVEL</button>
                    </a></td>
                </tr>
        </tbody>
    </table>

{% endblock %}

teacher/templates/teacher/student_promote.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Promote student {{ student.user.first_name }} {{ student.user.last_name  }}:</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
{% endblock %}

teacher/templates/teacher/students.html
{% extends 'base.html' %}

{% block title %}
    Student|Reunion detail 2
{% endblock %}
{% block content %}
    <h3>Students in current academic year:</h3>
    <table class="table">

        {% for level_number, data in students_by_level.items %}
            <thead class="thead-dark">
            <tr class="table-dark">
                <th scope="col" colspan="3">LEVEL {{ data.level }}</th>
            </tr>
            <tr class="table-secondary">
                <th scope="col" colspan="3">{{ lesson.topic }}</th>
            </tr>
            <tr>
                <th>FIRST NAME</th>
                <th>LAST NAME</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for student in data.students %}
                <tr>
                    <td>{{ student.user.first_name }}</td>
                    <td>{{ student.user.last_name }}</td>
                    <td><a href="{% url 'teacher:student-details' pk=student.id %}">
                        <button class="btn btn-sm btn-warning">DETAILS</button>
                    </a></td>
                </tr>
            {% endfor %}

        {% endfor %}
        </tbody>
    </table>

{% endblock %}