config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('student/items/', views.ItemsView.as_view(), name='items_view'),
    path('student/reunions/', views.ReunionsView.as_view(), name='reunions_view'),
    path('student/reunion/<int:pk>/', views.ReunionDetailView.as_view(), name='reunion-detail'),

]

teacher/urls.py
from django.urls import path

from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('rating/', views.RatingCreateView.as_view(), name='rating-create'),
    path('lesson/', views.LessonCreateView.as_view(), name='lesson-create'),
    path('lessons/', views.TeacherLessonsView.as_view(), name='lessons'),
    path('rating/<int:pk>/', views.RatingUpdateView.as_view(), name='rating-update'),
    path('lesson/<int:pk>/', views.LessonUpdateView.as_view(), name='lesson-update'),
    path('exam/<int:pk>/', views.ExamUpdateView.as_view(), name='exam-update'),
    path('exam/', views.ExamCreateView.as_view(), name='exam-create'),
    path('promote/', views.StudentsYearView.as_view(), name='promote'),
    path('student-details/<int:pk>/', views.StudentDetailView.as_view(), name='student-details'),
    path('exams/', views.TeacherExamsView.as_view(), name='exams'),
    path('exam/rating/<int:pk>/', views.ExamRatingUpdate.as_view(), name='exam-rating-update'),
    path('student/promote/<int:pk>/', views.PromoteView.as_view(), name='student-promote'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('', views.PasswordChange.as_view(), name='change_password'),
    path('academic-year/', views.ChooseAcademicYear.as_view(), name='change_academic_year'),
]

templates/partials/messages.html
{% if messages %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

templates/partials/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-warning" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="">
            <img class="logo" src="{% static 'images/Cross.webp' %}" alt="Logo LMS">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>

                {% if is_teacher and user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teacher:rating-create' %}">Create Rating</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teacher:lessons' %}">Lessons</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teacher:exams' %}">Exams</a>
                    </li>
                {% endif %}

                {% if is_student and user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:reunions_view' %}">Reunions</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:change_password' %}">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>


                {% endif %}
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% if request.session.current_academic_year and user.is_authenticated %}
        <span style="float:right">Academic year:<a class="nav-link"
                                                   href="{% url 'users:change_academic_year' %}">{{ request.session.current_academic_year }}</a></span>
    {% endif %}
</nav>