config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('student/items/', views.ItemsView.as_view(), name='items_view'),
    path('student/reunions/', views.ReunionsView.as_view(), name='reunions_view'),
    path('student/reunion/<int:pk>/', views.ReunionDetailView.as_view(), name='reunion-detail'),

]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('', views.PasswordChange.as_view(), name='change_password'),
    path('academic-year/', views.ChooseAcademicYear.as_view(), name='change_academic_year'),
]

student/models.py
from django.db import models
from django.conf import settings


class Student(models.Model):
    """school student model inherited from the user model"""

    class Confession(models.IntegerChoices):
        NOT_DEFINED = -1
        ROMAN_CATHOLIC = 0
        GREEK_CATHOLIC = 1
        ORTHODOX = 2
        OTHER = 3

    class Education(models.IntegerChoices):
        HIGHER = -1
        SECONDARY = 0
        VOCATIONAL = 1
        PRIMARY = 2
        OTHER = 3

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    academic_years = models.ManyToManyField('AcademicYear', related_name='students')
    phone = models.CharField(max_length=24)
    birth_date = models.DateField()
    confession = models.IntegerField(choices=Confession.choices, default=-1)
    education = models.IntegerField(choices=Education.choices, default=-1)
    address = models.TextField(blank=True)
    workplace = models.TextField(blank=True)
    comments = models.TextField(blank=True);
    index = models.CharField(max_length=24, blank=True, unique=True)
    diploma = models.CharField(max_length=24, blank=True, unique=False)
    level = models.ForeignKey('Level', related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} - level {self.level}"


class AcademicYear(models.Model):
    """We can manage academic years"""
    name = models.CharField(max_length=12)
    started_at = models.DateField()
    finished_at = models.DateField()
    items = models.ManyToManyField('Item', related_name='academicyears', through='StudentItemYear')

    def __str__(self):
        return f'{self.name}'


class Level(models.Model):
    """The school has three levels"""

    class LevelNumber(models.IntegerChoices):
        FIRST = 1
        SECOND = 2
        LAST = 3

    level_number = models.IntegerField(choices=LevelNumber.choices, default=1)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE, related_name="levels")

    def __str__(self):
        return f"{self.level_number} {self.academic_year}"


class Item(models.Model):
    """Model to manage school items"""
    name = models.CharField(max_length=128)
    students = models.ManyToManyField(Student, through='StudentItemYear', related_name='items')

    def __str__(self):
        return f"{self.name}"


class StudentItemYear(models.Model):
    """model describing M2M relationship between student, academic years and items """
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE)

    class Meta:
        """only one item student pair is possible in given academic year"""
        unique_together = ('student', 'item', 'academic_year',)

    def __str__(self):
        return self.student.user.first_name + " " + self.student.user.last_name + " " + " " + self.item.name + " " + self.academic_year.name

student/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views import View
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings

from teacher.models import Rating, Exam, StudentExam, Reunion, Teacher
from utlis import TeacherTestMixin, StudentTestMixin
from .models import AcademicYear, Item


# Create your views here.
class HomeView(StudentTestMixin, View):
    """Default view for all project. It redirects to correct view after successfull login """

    def get(self, request):
        current_academic_year = AcademicYear.objects.all().order_by('-started_at').first()
        if current_academic_year:
            request.session['current_academic_year'] = current_academic_year.name
        else:
            request.session['current_academic_year'] = "No academic year selected"
        return redirect(reverse('student:items_view'))

    def handle_no_permission(self):
        if TeacherTestMixin.is_teacher(self):
            return redirect(reverse('teacher:home'))
        elif self.request.user.is_superuser:
            return redirect(reverse('teacher:promote'))
        else:
            return redirect(reverse('users:login'))


class ItemsView(StudentTestMixin, View):
    """Items of logged student in chosen academic year"""

    def get(self, request):
        # check if user is a student, if not redirect him to login page
        current_academic_year = AcademicYear.objects.filter(name=request.session.get('current_academic_year')).first()
        items = Item.objects.filter(
            Q(academicyears__in=[current_academic_year]) & Q(students__in=[request.user.student])).order_by('name')
        ratings = Rating.objects.filter(student=request.user.student)
        exams = Exam.objects.filter(students__in=[request.user.student]).filter(academic_year=current_academic_year)
        ratings_exams = StudentExam.objects.filter(student=request.user.student)
        return render(request, 'student/home.html',
                      context={'ratings': ratings, 'items': items, 'exams': exams, 'ratings_exams': ratings_exams,
                               'is_student': True})


class ReunionsView(StudentTestMixin, ListView):
    """reunions in current academic year for logged students"""
    template_name = 'student/reunion_list.html'

    def queryset(self):
        current_academic_year = AcademicYear.objects.filter(
            name=self.request.session.get('current_academic_year')).first()
        queryset = Reunion.objects.filter(academic_year=current_academic_year).filter(
            level=self.request.user.student.level)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['is_student'] = True
        return context

    context_object_name = 'reunions'


class ReunionDetailView(StudentTestMixin, DetailView):
    """Details of specific reunion"""
    model = Reunion
    template_name = 'student/reunion_details.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['is_student'] = True
        return context

    context_object_name = 'reunion'

student/templates/student/home.html
{% extends 'base.html' %}
{% load student_extras %}

{% block title %}
    Student|Home
{% endblock %}

{% block content %}

    {% for item in items %}
        <table class="table">

            <thead class="thead-dark">
            <tr>
                <th scope="col" colspan="4">{{ item.name }}</th>
            </tr>
            {% for teacher in item.teachers.all %}
                <tr>
                    <th scope="col" colspan="4">{{ teacher }}</th>
                </tr>
            {% endfor %}
            <tr>
                <th></th>
                <th>RATING</th>
                <th>NOTICE</th>
                <th>TEACHER</th>
            </tr>
            </thead>
            <tbody>

            {% for rating in ratings|in_item:item %}
                <tr>
                    <th scope="row">{{ rating.date }}</th>
                    <td>{{ rating.value }}</td>
                    <td>{{ rating.notice }}</td>
                    <td>{{ rating.teacher }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <table class="table">

            {% for exam in exams|in_item:item %}
                <thead class="thead-light">
                <tr>
                    <th scope="col" colspan="3">Exam</th>
                </tr>
                <tr>
                    <th></th>
                    <th></th>
                    <th>RATING</th>
                </tr>
                </thead>
                <tbody>

                {% for rating_exam in ratings_exams|in_exam:exam %}
                    <tr>
                        <th scope="row">{{ exam.date_time }}</th>
                        <td>{{ exam.localization }}</td>
                        <td>{{ rating_exam.rating }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            {% endfor %}
        </table>
    {% endfor %}

{% endblock %}

student/templates/student/reunion_details.html
{% extends 'base.html' %}

{% block title %}
    Student|Reunion detail 2
{% endblock %}
{% block content %}
<h3>Lessons for reunion from {{ reunion.start_at }} to {{ reunion.finish_at }}:</h3>
<table class="table">

    {% for lesson in reunion.lessons.all|dictsortreversed:'date_time' %}
        <thead class="thead-dark">
            <tr class="table-dark">
                 <th scope="col" colspan="4">{{ lesson.item }}</th>
            </tr>
            <tr class="table-primary">
                 <th scope="col" colspan="4">{{ lesson.teacher }}</th>
            </tr>
            <tr class="table-secondary">
                 <th scope="col" colspan="4">{{ lesson.topic }}</th>
            </tr>
            <tr>
                <th></th>
                <th>Date Time</th>
                <th>Localization</th>
                <th>References</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <th scope="row"></th>
                <td>{{ lesson.date_time }}</td>
                <td>{{ lesson.localization }}<br />{{ lesson.localization.address }}</td>
                {% if lesson.references %}
                <td><a href="{{ MEDIA_URL }}{{ lesson.references }}" download>DOWNLOAD</a></td>
                {% else %}
                <td></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

student/templates/student/reunion_list.html
{% extends 'base.html' %}
{% load student_extras %}

{% block title %}
    Student|Reunions
{% endblock %}

{% block content %}
    <h2>Reunions for your level in this academic year:</h2>
    <ul class="list-group">
    {% for reunion in reunions|dictsortreversed:"start_at" %}
        <li class="list-group-item"><a href="{% url 'student:reunion-detail' pk=reunion.id %}">{{ reunion.academic_year }} - {{ reunion.start_at }} - {{ reunion.finish_at }}</a></li>
        {% empty %}
        <li class="list-group-item">No reunions found.</li>
    {% endfor %}
    </ul>

{% endblock %}